import type {Metadata} from 'next'
import localFont from 'next/font/local'

import styles from '@/app/common/styles.module.css'
import './globals.css'
import Image from 'next/image'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'FormEngine with Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <main className={styles.main}>
      <div className={styles.page}>
        {children}
      </div>
      <footer className={styles.footer}>
        <a
          href="https://formengine.io/documentation/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/file.svg"
            alt="FormEngine documentation"
            width={16}
            height={16}
          />
          Documentation
        </a>
        <a
          href="https://formengine.io/documentation/usage-with-nextjs"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/file.svg"
            alt="FormEngine usage with NextJS"
            width={16}
            height={16}
          />
          With Next.js
        </a>
        <a
          href="https://formengine.io/pricing"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/globe.svg"
            alt="FormEngine"
            width={16}
            height={16}
          />
          FormEngine
        </a>
      </footer>
    </main>
    </body>
    </html>
  )
}
